### PR TITLE
Fix duplicate data columns in DataColumnsByRange responses

### LINKED ISSUE #8842: Regression in `DataColumnsByRange` responses (duplicates included)
## Description

This line is wrong:

https://github.com/sigp/lighthouse/blob/2f7a1f3ae8b450f8042001a67ae88dd675251e3c/beacon_node/network/src/network_beacon_processor/rpc_methods.rs#L979-L980

Regression was introduced in:

- #8682

The method previously returned `Vec<Hash256>` which de-duplicated correctly. But now returns `Vec<(Hash256, Slot)>` which does not de-duplicate blocks correctly because the slots are unique. This results in duplicate columns being served to peers, and down-scoring by those peers (`DuplicatedData` errors).

## Version

This is a bug in v8.1.0 only.

### PR DESCRIPTION
**Pull request by jimmygchen**
## Description

Fix a regression introduced in #8682 where `get_block_roots_from_store` returns duplicate block roots for skip slots, causing duplicate data columns to be served in `DataColumnsByRange` responses. Peers receiving these duplicates downscore the node with `DuplicatedData` errors.

The return type was changed from `Vec<Hash256>` to `Vec<(Hash256, Slot)>`, but `.unique()` on tuples no longer deduplicates correctly because skip slots share the same block root but have different slots. Fix by using `.unique_by(|(root, _)| *root)`.

Closes #8842

### CODE REVIEW

File: beacon_node/network/src/network_beacon_processor/rpc_methods.rs [hunk 1]
```diff
@@ -977,7 +977,10 @@ impl<T: BeaconChainTypes> NetworkBeaconProcessor<T> {
         };
 
         // remove all skip slots i.e. duplicated roots
-        Ok(block_roots.into_iter().unique().collect::<Vec<_>>())
+        Ok(block_roots
+            .into_iter()
+            .unique_by(|(root, _)| *root)
+            .collect::<Vec<_>>())
```
Comment (michaelsproul) [inline beacon_node/network/src/network_beacon_processor/rpc_methods.rs:983]: Can we add a test for this? From memory there are some tests in this file.

Comment (jimmygchen) [reply beacon_node/network/src/network_beacon_processor/rpc_methods.rs:983]: yes absolutely! working on a test now

Comment (jimmygchen) [reply beacon_node/network/src/network_beacon_processor/rpc_methods.rs:983]: https://github.com/sigp/lighthouse/pull/8843/commits/84a77be4460f1dfd4c0add78a6788e9a26e5c5e3

**Comment by michaelsproul** [comment]
@jimmygchen Just needs a cargo fmt

**Comment by jimmygchen** [comment]
Thanks @michaelsproul!

We really should merge this lol
* https://github.com/sigp/lighthouse/pull/8715

**Review by michaelsproul — APPROVED** [review]
Looks good. Test logic makes sense (request 1 column over a range of slots -> block roots should be unique).
