### PR TITLE
Fix race condition in VC block proposal service

### LINKED ISSUE #918: Validator client race condition leading to missed duties
## Overview

There's a race condition in the validator client that can lead to blocks and attestations being missed.

## Setup

The validator client (specifically, the [`DutiesService`](https://github.com/sigp/lighthouse/blob/master/validator_client/src/duties_service.rs)) periodically polls for duties for the current and next epoch (according its slot clock). It stores these duties in its [`DutiesStore`](https://github.com/sigp/lighthouse/blob/c198bddf9e5f21b99756561c55f4bac799245de3/validator_client/src/duties_service.rs#L71-L74) so that the [`BlockService`](https://github.com/sigp/lighthouse/blob/master/validator_client/src/block_service.rs) and [`AttestationService`](https://github.com/sigp/lighthouse/blob/master/validator_client/src/attestation_service.rs) can know when to produce blocks/attestations.

Previously, before an eth2 spec update (I forget which one, perhaps v0.10.0) the only reason the validator duties could change was due to a fork. However, since that aforementioned spec update we only have a 1-epoch look-ahead on proposer duties (since [`compute_proposer_index`](https://github.com/sigp/lighthouse/blob/b1d23ec29422f7feb99677970c166addc015afe2/eth2/types/src/beacon_state.rs#L391-L428) relies upon the effective balance for `state.validators`, which can change on any epoch boundary).

So, prior to this spec change this race condition existed but it was not obvious or part of routine, best-case operation. After this spec change, this race condition is expected to happen commonly, even without a forking chain.

## The race condition

The validator client periodically polls for duties for the current and next epoch (according its slot clock). If it detects a change in duties, it simply updates its internal data-store and continues on. It does not trigger the `BlockService` or `AttestationService` to try and produce a block/attestation based upon these duties.

So, we have the following race condition:

1. In epoch `E - 1`, we check the duties and see that validator `V` should produce a block at the 2nd slot of epoch `E`.
1. Epoch `E` arrives. 
1. The [`BlockService::do_update`](https://github.com/sigp/lighthouse/blob/b1d23ec29422f7feb99677970c166addc015afe2/validator_client/src/block_service.rs#L158) and the [`DutiesService::do_update`](https://github.com/sigp/lighthouse/blob/b1d23ec29422f7feb99677970c166addc015afe2/validator_client/src/duties_service.rs#L367) function are both triggered simultaneously.
1. The `BlockService` completes first, finding that validator `V` does not need to produce till the 2nd slot of epoch `E` (it is the 1st slot now).
1. Then, `DutiesService` completes, finding that the block proposing duty for `V` has moved to the 1st slot of epoch `E`.

Since the `BlockService` has already completed it's poll for this slot, it ends up producing a block in the 1st slot.

## Potential solutions

1. Have the `BlockService` and `AttestationService` multiple times per slot (e.g., 0%, 50%, 80% through the slot).
1. Have the `DutiesService` trigger an update on `BlockService` and `AttestationService` whenever it finds a duties change.

(1) is simple to implement, however it is inefficient (will check for changes when none have occurred) and it doesn't completely solve the race-condition (it just mitigates).

(2) is more difficult to implement however it's an efficient and complete solution to the problem. The main obstacle I see is that `BlockService` and `AttestationService` already have a reference to `DutiesService`, so adding references back is circular. We could solve this using a [futures channel](https://docs.rs/futures/0.3.4/futures/channel/mpsc/index.html) for each of the `BlockService` and `AttestationService`, where the `DutiesService` holds a sender and publishes an event to the relevant service when there's a duties update. That being said, throwing channels around the place can get a bit messy, so perhaps there's a tidier solution (e.g., the `DutiesService` holds optional references to the other services which are updated after instantiation).

### LINKED ISSUE #923: BeaconState::get_beacon_proposer_index should check slot
## Description

The `BeaconState::get_beacon_proposer_index` function should check that the `slot` argument lies within sensible bounds before attempting to compute a proposer index. Proposer indices are only known for the current epoch and earlier due to the possibility of a validator's effective balance changing upon the next epoch boundary. The lower bound is likely related to the lower bound for the active validator indices (see #922), but could probably be set to the previous epoch for all current uses.

### PR DESCRIPTION
**Pull request by michaelsproul**
## Issues Addressed

Closes #918
Closes #923

## Proposed Changes

- Checks that `BeaconState::get_beacon_proposer_index` is only called on slots from the state's current epoch (fixing #923)
- Uses a channel between the validator client's duties service and block service instead of relying on a timing assumption. All the interval futures have now been removed from the block service in favour of the duties service's time-keeping. This fixes the race condition of #918, and importantly gives the block service a better chance of proposing in the first slot of each epoch, immediately after the proposer for that slot is discovered in a duties update.

## Additional Info

- I had to hack around with the rest API's `get_state_for_epoch`, mostly in order to get it to transition a state to the first slot of the epoch when the head is at the last slot of the previous epoch. The comment on `TIME_DELAY_FROM_SLOT` implies that the beacon node may do this (or other?) processing passively, which doesn't seem to be the case. I wonder if we could decrease that 100ms delay to get tasty async block proposals even closer to the start of the slot. https://github.com/sigp/lighthouse/blob/710409c2bafbd118ac8a9a4115ed7a8abfe9929a/validator_client/src/duties_service.rs#L16-L17
- The implementation of `ValidatorDutyBase::eq_ignoring_proposal_slots` is a bit hacky, but seemed to be the best I could do without:
    + Refactoring `ValidatoryDutyBase` into two separate structs, or
    + Using something like [`multi-eq`](https://crates.io/crates/multi-eq) (messy in its own way), or
    + Using `derivative` to ignore the `proposal_slots` field in the standard `PartialEq` impl (risky!)
- I might add some checks to the simulator to ensure that a block is proposed for every slot
- This PR should probably be merged after #1227

### CODE REVIEW

File: validator_client/src/duties_service.rs [hunk 1]
```diff
@@ -522,14 +543,29 @@ impl<T: SlotClock + 'static, E: EthSpec> DutiesService<T, E> {
...
             .update_epoch(current_epoch + 1)
             .await
-            .map_err(move |e| {
+            .map_err(|e| {
                 error!(
                     log,
                     "Failed to get next epoch duties";
                     "http_error" => format!("{:?}", e)
                 );
             })?;
```
Comment (michaelsproul) [inline validator_client/src/duties_service.rs:552]: @paulhauner To address your concern about block production not running when duties updates fail, what if we moved the channel broadcast (below) above this block that performs the update for the next epoch? Or we could change the next epoch update to be the same as the current epoch update above it (using `if let Err(e)` to log the error and keep running).

I'd prefer to do something like this than reintroduce the interval timer, because I think having the duties service act as the canonical source of time helps prevent inconsistency between the two services, and stops us from having to think about the block service running twice in every slot. With re-orgs, the block proposer duties could change mid-epoch, and we wouldn't want to produce a block using the old duties (on the interval) only to then get a duties update and realise we produced incorrectly.

Comment (paulhauner) [reply validator_client/src/duties_service.rs:552]: > what if we moved the channel broadcast (below) above this block that performs the update for the next epoch?

Yep, that solves my issue! Great alternative.
