### PR TITLE
Fix `DataColumnsByRoot` request limit validation bug

### LINKED ISSUE #7926: Seeing immediate stream terminations on `DataColumnsByRoot` messages
@pawanjay176 noticed this issue while running a node, and this seems to be causing problems for sync

> There's something very weird about the DataColumnsByRoot message at the rpc messaging level. A simple rpc test of sending a request and receiving the required response fails by the receiver not showing any request recceived and the sender getting an immediate stream termination

This happens also on LH <> LH nodes, as a simple test in `rpc_tests.rs` confirms it's reproducible.

This failure is likely to cause issues on block lookups, and should also be reproducible with `./genesis-sync.sh` with 120s wait.

### PR DESCRIPTION
**Pull request by jimmygchen**
## Issue Addressed

Fixes #7926

This was a bug I introduced in #7890 and @pawanjay176 noticed it on some running nodes, and added a rpc test to confirm it.

The culprit is this line, where I failed to fill the vec to it's max size, so it doesn't calculate the max size properly, resulting in all `DataColumnByRoot` requests exceeding the max size during validation:
https://github.com/sigp/lighthouse/blob/d24a6d2a45f25dfdba8740d10c569226555a8143/consensus/types/src/chain_spec.rs#L1984

The PR fixes this and includes new regression tests for this fix.

### CODE REVIEW

File: beacon_node/lighthouse_network/tests/rpc_tests.rs [hunk 1]
```diff
@@ -949,6 +950,303 @@ fn test_tcp_blocks_by_root_chunked_rpc() {
...
+            Arc::downgrade(&rt),
+            current_fork_name,
+            spec.clone(),
+            Protocol::Tcp,
+            false,
+            None,
+        )
+        .await;
+
+        // BlocksByRoot Request
```
Comment (jimmygchen) [inline beacon_node/lighthouse_network/tests/rpc_tests.rs]: Comment need update

File: beacon_node/lighthouse_network/tests/rpc_tests.rs [hunk 2]
```diff
@@ -949,6 +950,303 @@ fn test_tcp_blocks_by_root_chunked_rpc() {
...
+
+        let rpc_request = RequestType::DataColumnsByRange(DataColumnsByRangeRequest {
+            start_slot: 320,
+            count: 32,
+            columns: (0..128).collect(),
+        });
+
+        // DataColumnsByRoot Response
```
Comment (jimmygchen) [inline beacon_node/lighthouse_network/tests/rpc_tests.rs]: This one too

**Review by pawanjay176 — APPROVED** [review]
LGTM, thanks for fixing this up.
