### PR TITLE
Interop

### LINKED ISSUE #482: Problems with BeaconChain::current_state(..)
## Description

Presently we keep a [`state`](https://github.com/sigp/lighthouse/blob/89cb01cc93c637ca489a01e5867c80690eb4ed9a/beacon_node/beacon_chain/src/beacon_chain.rs#L76-L79) field on the `BeaconState`. Each time the slot-clock ticks, we advance it to ensure it's up-to-date with the current slot (we call this process a "catch up").

This was originally added as a sort-of cache to ensure we can produce blocks at the current slot quickly (i.e., without doing lots of `per_slot_processing`). It serves this purpose well, except it has two issues:

1. When the distance between the current slot (i.e., wall-clock slot) and the latest state we have is large (e.g., when first booting a node) a lot of time (seconds, minutes, hours) can be spent updating this state. This frequently happens when booting a fresh node some time after genesis.
1. The state in question is exposed via `BeaconChain::current_state(..)`. This state has an interesting problem that neither it or all of it's ancestors are stored in the database (see #481). Considering that the difference between `beacon_chain.head().beacon_state` and `beacon_chain.current_state()` is not intuitive, it seems that users are likely to make mistakes (I have) and therefore allowing public access to this state is error prone.

## Steps to resolve

Firstly, I propose that we ensure that `beacon_chain.state` is not publicly accessible (i.e., remove the `BeaconChain::current_state(..)` method). If any caller decides that they want a state _later_ than the state of the head block, then they can explicitly do the state advancement themselves (it's not difficult, just call `state_processing::per_slot_processing(..)` a bunch of times).

Secondly, I propose that we re-purpose the `state` field to be exclusively for block (and maybe attestation) production and we add a `MAX_CATCHUP` value whereby we don't try to catch-up the state beyond that. For example, when we boot up a new beacon node, it runs `BeaconState::catchup_state(..)` from genesis through to the current slot -- this can take a very long time. The `MAX_CATCHUP` value will limit the time this takes, however it will have the downside that _if_ the node is used for block production then it will be necessary to do a full catchup (beyond `MAX_CATCHUP`). This is good in some ways, because it means that we only do a big catchup when necessary. However, there is the downside that if this catch-up takes several minutes a validator client connected via HTTP will probably time-out and give up. Such a case would only exist when there is a massive number of skipped slots -- this _should_ never happen on the production chain but may be encountered during testing. I think this is a bit of a structural issue with the spec and something that we need to accept for now.

### LINKED ISSUE #503: CLI strategy
## Problem

We have several months of testing ahead of us that's going involve starting and restarting the `beacon_node` binary  in all different configurations. E.g., during the interop event we're going to be using several different configurations per day.

The CLI interface is getting a little cluttered and it's not clear as to what's going to happen. For example:

- What happens if I give a different `--spec` flag to whats in the on-disk config?
- What if I already have a database initialized with a different genesis state?
- How do I know what params I need to give in order to start from some interop method?

## Proposal

I say there's two main use cases:

- **Resuming** an existing node (e.g., load from an existing datadir/DB).
- Starting a **new node** from one of many genesis-procedures (HTTP bootstrap, genesis yaml, etc) with some spec (e.g., minimal, mainnet, custom).

To suite these two purposes, we utilize clap `subcommands` to separate between these two tasks:

- `$ ./beacon_node` (no args): is a "resume" operation.
  - If there is a datadir and DB, it's business as usual.
  - If there's no existing DB we throw an error and tell the user to use the `testnet` subcommand.
  - Once we have a big testnet or mainnet, we can make the assumption that if no DB exists, they want to connect to this testnet.
  - Does not accept a `--spec` flag. You're either using the default or an existing config. No choice for you.
- `$ ./beacon_node testnet`: is a "new node" operation. 
  - If the `datadir` already exists, return an error (avoids overwriting, confusion about whether or not TOML files will be effective).
  - We can specify a `--force` flag that will remove any existing `datadir`.
  - We can also specify a `--tmp` flag that just crates a random datadir in the `/tmp` dir.
  - Accepts a `--spec` flag. Can haz choice here.

### Testnet examples

Start a testnet node from the given YAML file and the minimal spec:
```
$ ./beacon_node testnet yaml ~/genesis_state.yaml --spec mainnet
```

Start a testnet node with 100 nodes using "recent genesis" and mainnet spec:
```
$ ./beacon_node testnet recent 100 --spec mainnet
```

Start a testnet node from another lighthouse node using Bootstrap™
```
$ ./beacon_node testnet bootstrap http://192.168.1.2
```

##  Pros

- You don't ever accidentally start from an existing DB when you wanted to start anew.
- Using `subcommands` we get name-spacing for CLI flags. E.g., if `bootstrap` needs the `--ssl` flag, we can add it to that subcommand without it showing up everywhere else.
- It'll be very obvious when you're missing a flag required for an interop method (clap can know some flag is required for a subcommand).
- You only ever need to worry about the TOML files if you want to change them.
- Doesn't over-write config files.
- Doesn't ignore config files.

## Cons

- Having to type `testnet` is additional work.
- Need to think about whether or not you're starting new or not (arguably a pro).

### LINKED ISSUE #519: Issue in README "Simple Local Testnet"
## Description

When going to Step 3 ([Start Another Beacon Node](https://github.com/sigp/lighthouse#3-start-another-beacon-node)) in the readme simple testnet instructions, the second node fails due to a collision in the RestAPI port.

## Present Behaviour

The current behaviour is that `./beacon_node` defaults to having the Rest API enabled due to the following default config.

https://github.com/sigp/lighthouse/blob/c4ced3e0d25f40e14c2f47a43285da4faf350a01/beacon_node/rest_api/src/config.rs#L16-L24

Because both `beacon_node` programs are attempting to run with the default port (5052), the second has a collision and crashes. You can run the second with `--api-port <no-5052>` as a quick fix.

More importantly, the way `--api` command line option is configured, you can't actually turn the rest api server _off_ because this value defaults to `enabled` when no param is given. When the param is given, `--api` just triggers it to be on, so it's on always.

## Expected Behaviour

Should be able to just run the commands in the quickstart without error. The quickfix is to just add an `--api-port` command to the quickstart step 3. 

The deeper fix is to reconsider how the rest api should be controlled.

Should probably do one of the following:
- `--api` should accept True/False
- `--api` should be swapped for a flag that disables the api server (eg `--no-api` or `--api-off`)
- the API server should be turned off by default with the `--api` flag turning it on

## Steps to resolve

- fix quickstart instructions
- fix up `--api` so it can actually be turned on and off

Please describe the steps required to resolve this issue, if known.

### LINKED ISSUE #539: Underflow when subtracting duration in tests
## Description

Reported here: https://github.com/sigp/lighthouse/pull/536#issuecomment-532581833

Thanks to @pscott for pointing it out!

## Additional Info

I'm pretty sure this is to do with the slot clock. Shouldn't be too hard to resolve.

Note: the issue is on the `interop` branch, not master.

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

- Resolves #503
- Resolves #519
- Resolves #482
- Resolves #539

## Description

This branch was created prior to the September 2019 interop workshop in Skeleton Lake, Canada. It contains an unusually large amount of work for a single PR. It was created prior to the event, updated during the event and patched after the event.

## Proposed Changes

Changes include (but are certainly not limited to):

- Adds a `testnet` subcommand to the CLI to facilitate creating testnets.
- Changes `seconds_per_slot` to `milliseconds_per_slot` to allow for faster testnets.
- Fixes bugs in fork choice, improves logging.
- Runs an integrity check on fork choice whenever processing a block fails.

### CODE REVIEW

File: beacon_node/beacon_chain/src/beacon_chain.rs [hunk 1]
```diff
@@ -33,6 +38,12 @@ use types::*;
 //                          |-------must be this long------|
 pub const GRAFFITI: &str = "sigp/lighthouse-0.0.0-prerelease";
 
+/// If true, everytime a block is processed the pre-state, post-state and block are written to SSZ
+/// files in the temp directory.
+///
+/// Only useful for testing.
+const WRITE_BLOCK_PROCESSING_SSZ: bool = true;
```
Comment (michaelsproul) [inline beacon_node/beacon_chain/src/beacon_chain.rs]: This would be nice behind a feature flag, `const WRITE_BLOCK_PROCESSING_SSZ: bool = cfg!(feature = "write_block_processing_ssz")`

File: beacon_node/beacon_chain/src/beacon_chain.rs [hunk 2]
```diff
@@ -300,60 +354,74 @@ impl<T: BeaconChainTypes> BeaconChain<T> {
...
+    ///  to a future state.
+    pub fn state_at_slot(&self, slot: Slot) -> Result<BeaconState<T::EthSpec>, Error> {
+        let head_state = self.head().beacon_state;
+
+        if slot == head_state.slot {
+            Ok(head_state)
+        } else if slot > head_state.slot {
+            let head_state_slot = head_state.slot;
+            let mut state = head_state.clone();
+            drop(head_state);
```
Comment (michaelsproul) [inline beacon_node/beacon_chain/src/beacon_chain.rs]: Clone and drop seems strange, could just move `let mut state = head_state;`

File: beacon_node/beacon_chain/src/beacon_chain_builder.rs [hunk 3]
```diff
@@ -0,0 +1,334 @@
...
+    state.genesis_time = genesis_time;
+
+    // Invalid all the caches after all the manual state surgery.
+    state.drop_all_caches();
+
+    Ok(state)
+}
+
+/// Returns `int` as little-endian bytes with a length of 32.
+fn int_to_bytes32(int: usize) -> Vec<u8> {
```
Comment (michaelsproul) [inline beacon_node/beacon_chain/src/beacon_chain_builder.rs]: Should delete this

File: beacon_node/beacon_chain/src/eth1_chain.rs [hunk 4]
```diff
@@ -0,0 +1,110 @@
...
+impl<T: EthSpec> Default for InteropEth1ChainBackend<T> {
+    fn default() -> Self {
+        Self {
+            _phantom: PhantomData,
+        }
+    }
+}
+
+/// Returns `int` as little-endian bytes with a length of 32.
+fn int_to_bytes32(int: u64) -> Vec<u8> {
```
Comment (michaelsproul) [inline beacon_node/beacon_chain/src/eth1_chain.rs]: Delete

File: beacon_node/eth2-libp2p/src/service.rs [hunk 5]
```diff
@@ -42,16 +42,22 @@ impl Service {
...
+        let local_keypair = if let Some(hex_bytes) = &config.secret_key_hex {
+            keypair_from_hex(hex_bytes)?
+        } else {
+            load_private_key(&config, &log)
+        };
+
         // load the private key from CLI flag, disk or generate a new one
-        let local_private_key = load_private_key(&config, &log);
-        let local_peer_id = PeerId::from(local_private_key.public());
+        // let local_private_key = load_private_key(&config, &log);
```
Comment (michaelsproul) [inline beacon_node/eth2-libp2p/src/service.rs]: Commented out

File: beacon_node/network/src/message_handler.rs [hunk 6]
```diff
@@ -65,7 +73,11 @@ impl<T: BeaconChainTypes + 'static> MessageHandler<T> {
                 .for_each(move |msg| Ok(handler.handle_message(msg)))
                 .map_err(move |_| {
                     debug!(log, "Network message handler terminated.");
-                }),
+                }), /*
+                    .then(move |_| {
+                        debug!(log.clone(), "Message handler shutdown");
+                    }),
+                    */
```
Comment (michaelsproul) [inline beacon_node/network/src/message_handler.rs]: Commented

File: beacon_node/network/src/sync/manager.rs [hunk 7]
```diff
@@ -401,92 +624,124 @@ impl<T: BeaconChainTypes> ImportManager<T> {
...
-                peer_id: peer_id.clone(),
-                request,
-                request_id,
-            });
-        }
-
-        None
-    }
+        for (peer_id, block_requests) in self.import_queue.iter_mut() {
+            {
```
Comment (michaelsproul) [inline beacon_node/network/src/sync/manager.rs]: This extra block scope seems unnecessary

File: eth2/utils/ssz/src/encode.rs [hunk 8]
```diff
@@ -27,6 +27,8 @@ pub trait Encode {
         BYTES_PER_LENGTH_OFFSET
     }
 
+    fn ssz_bytes_len(&self) -> usize;
```
Comment (michaelsproul) [inline eth2/utils/ssz/src/encode.rs]: Would be nice to have a doc comment on this

File: lcli/src/pycli.rs [hunk 9]
```diff
@@ -0,0 +1,123 @@
...
+            } else if filename.starts_with(POST_PREFIX) {
+                dbg!("post state");
+            } else {
+                dbg!("unknown file");
+            }
+
+            Ok(())
+        })
+}
+*/
```
Comment (michaelsproul) [inline lcli/src/pycli.rs]: Do you.. want this?

File: lcli/src/transition_blocks.rs [hunk 10]
```diff
@@ -0,0 +1,93 @@
...
+    output_file
+        .write_all(&post_state.as_ssz_bytes())
+        .map_err(|e| format!("Unable to write to output file: {:?}", e))?;
+
+    /*
+    println!(
+        "{}",
+        serde_yaml::to_string(&post_state).expect("Should serialize state")
+    );
+    */
```
Comment (michaelsproul) [inline lcli/src/transition_blocks.rs]: Commented out
