### PR TITLE
Reuse password option prompts again on a wrong password

### LINKED ISSUE #4364: `--reuse-password` fails to check if the reused password is correct
## Description

When using the `account validator import` command with `--reuse-password` flag, the password will be reused and the keystores will be imported even if the password is wrong after the first successful keystore import.

## Version

Lighthouse v4.2.0-c547a11 (from v4.2.0 stable release on Ubuntu 22.04)

## Present Behaviour

If you create multiple keystores with different passwords and import them all with a command like:
```
sudo ./lighthouse account validator import --reuse-password \
    --directory /home/remyroy/staking_deposit-cli-d7b5304-linux-amd64/validator_keys \
    --datadir /var/lib/lighthouse \
    --network mainnet
```
it will prompt for the first keystore password and if that password is correct, the import command will import all the keystores with the same password not matter if the password is correct or not.

## Expected Behaviour

The import command should check each keystore to make sure the imported password is correct. If one password check fails, it should prompt for a new password (ideal for most use cases) or stop with an error message.

## Steps to resolve

Modify the behavior of the `account validator import` command with `--reuse-password` flag to check for each keystore to make sure the password is working and prompt for a new password if not.

### PR DESCRIPTION
**Pull request by pawanjay176**
## Issue Addressed

Resolves #4364 

## Proposed Changes

Prompt the user to enter the password if the password is incorrect on using the `reuse-password` flag. 
This is useful when importing multiple keystores for which there are more than 1 passwords.

cc @remyroy

### CODE REVIEW

**Review by michaelsproul — DISMISSED** [review]
Code LGTM, has anyone tested in manually?

**Comment by remyroy** [comment]
I manually tested it and it worked for me.

**Comment by pawanjay176** [comment]
Just changed a match statement to if in [95518f6](https://github.com/sigp/lighthouse/pull/4380/commits/95518f634b0b59bedcb1bd357622121109d4a63c)

**Comment by pawanjay176** [comment]
@chong-he Found a bunch of edge cases not properly handled. Need to fix those

**Comment by remyroy** [comment]
Is there any update on this PR? It would be nice to fix #4364

**Comment by chong-he** [comment]
@remyroy 

After some testing, it was found that the PR requires a fix. Consider a scenario we have 2 keystore files with `passwordA`, and 3 keystore files with `passwordB`

When we `import` the keys, it is all good for the first 2 keystore files. Then it will detect that the third keystore file has a different password, which it will prompt the user to input a new password. The problem is: the UX doesn't check if the password is correct or not, and will import the validator regardless (including the case when a user enters a wrong password) and show:
`Successfully imported keystore`
`Successfully updated validator_definitions.yml.`

It also wouldn’t show whether the password is correct or not. 

It will then proceed to the fourth keystore, which it will now be able to detect the incorrect password and prompt again for the correct password.

I attach a screenshot for reference.

pass

File: account_manager/src/validator/import.rs [hunk 1]
```diff
@@ -169,7 +169,15 @@ pub fn cli_run(matches: &ArgMatches, validator_dir: PathBuf) -> Result<(), Strin
...
             if let Some(password) = previous_password.clone() {
                 eprintln!("Reuse previous password.");
-                break Some(password);
+                if check_password_on_keystore(&keystore, &password)? {
+                    break Some(password);
+                } else {
+                    eprintln!("Reused password incorrect. Retry!");
+                    if let Some(password) = get_password(stdin_inputs) {
+                        previous_password = Some(password.clone());
+                        break Some(password);
```
Comment (chong-he) [inline account_manager/src/validator/import.rs]: The current issue is that upon a reused password, after prompting the user to enter the password (line 177), it does not check whether the password is correct or not and proceed to the next keystore regardless. So I added a call to `check_password_on_keystore` to check the password. 
```suggestion
                        previous_password = Some(password.clone());
                        if check_password_on_keystore(&keystore, &password)? {
                        break Some(password);
                        }
```
The issue now is, because it becomes a nested if loop, the UX when the password is incorrect becomes:
`Invalid password`
at a first try, and then jumps to the beginning of the loop and display:
```
Invalid password
Reuse previous password.
Invalid password
Reused password incorrect. Retry!
```
and alternating that way until a correct password is entered. Do we have a better way for the UX? I try using a while loop but that's weird outcome too

Comment (pawanjay176) [reply account_manager/src/validator/import.rs]: Fixed in [bd035f9](https://github.com/sigp/lighthouse/pull/4380/commits/bd035f9f5b3cc4f14e549ca2f2795c7b76ebea3a)

Thanks for catching it and testing the fix CK :)

**Comment by pawanjay176** [comment]
@remyroy Sorry for the delay, this one went under the radar.

Fixed the issues now.

**Comment by chong-he** [comment]
I have tested the feature and can confirm that it is working

**Review by dapplion — APPROVED** [review]

**Comment by jimmygchen** [comment]
@mergify queue
