### PR TITLE
Fix data availability checker race condition causing partial data columns to be served over RPC

### LINKED ISSUE #6439: Same block getting imported multiple times due to race condition
## Description

**TL;DR:** This is actually an existing race condition and can be triggered today. This can happen when blobs arrived from RPC and gossip around the same time and both triggering a block import. There's no impact other than extra work performed:  in the 2nd import, the state cache is expected to miss, as the previous import `pop`'d the state, so this will result in state reconstruction, which takes ~80ms.

### PeerDAS occurence

On `peer-das-devnet-2`, I'm seeing the same block getting written to the database multiple times (4 times within 2 ms!). This occurred on a supernode.

I think this is because we keep the `PendingComponent`s in the cache until we complete block import, so for each gossip component that made it through to the DA checker after the block is available, it would trigger another import:

https://github.com/sigp/lighthouse/blob/07afa6c2a57e5eff515482a62e064ff975e36966/beacon_node/beacon_chain/src/beacon_chain.rs#L3635-L3646

With PeerDAS supernodes, once we receive 64 columns, the remaining columns can come from reconstruction and block can be made available after this. However, we can still get columns from gossip (as they haven't been seen via gossip), and each of these gossip columns could trigger a block import, as the `PendingComponent` in the cache is "complete".

The change to keep `PendingComponent` in the DA cache was intentional and was made in the following PR to address an issue with sync lookup:
https://github.com/sigp/lighthouse/pull/5845

I'm not sure if there's a better way, but if we do need to keep the block in the DA Checker during import, perhaps we can do a check before trying to process a gossip block/blob/data_column  - if block has already been made available, just `return` instead of processing and re-importing.

### PR DESCRIPTION
**Pull request by jimmygchen**
## Issue Addressed

Partially resolves #6439, an simpler alternative to #7931.

Race condition occurs when RPC data columns arrives after a block has been imported and removed from the DA checker:
 1. Block becomes available via gossip
 2. RPC columns arrive and pass fork choice check (block hasn't been imported)
 3. Block import completes (removing block from DA checker)
 4. RPC data columns finish verification and get imported into DA checker

This causes two issues:
1. **Partial data serving**: Already imported components get re-inserted, potentially causing LH to serve incomplete data
2. **State cache misses**: Leads to state reconstruction, holding the availability cache write lock longer and increasing race likelihood

### Proposed Changes

1. Never manually remove pending components from DA checker. Components are only removed via LRU eviction as finality advances. This makes sure we don't run into the issue described above.
2. Use `get` instead of `pop` when recovering the executed block, this prevents cache misses in race condition. This should reduce the likelihood of the race condition
3. Refactor DA checker to drop write lock as soon as components are added. This should also reduce the likelihood of the race condition

**Trade-offs:**

This solution eliminates a few nasty race conditions while allowing simplicity, with the cost of allowing block re-import (already existing). 

The increase in memory in DA checker can be partially offset by a reduction in block cache size if this really comes an issue (as we now serve recent blocks from DA checker).

### CODE REVIEW

**Comment by shane-moore** [comment]
cool that this will simplify concurrency management for the DA checker

as a follow-up, it might be good to monitor memory usage in grafana after deploying to a devnet as to keep an eye on it

File: beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs [hunk 1]
```diff
@@ -22,6 +24,31 @@ use types::{
     Hash256, RuntimeFixedVector, RuntimeVariableList, SignedBeaconBlock,
 };
 
+pub enum CachedComponents<E: EthSpec> {
+    Pending(PendingComponents<E>),
+    Available(PendingComponents<E>),
+}
```
Comment (jimmygchen) [inline beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs]: Enum wrapper now unused, and we can remove this to simplify this PR. 

I originally added this so we can do early returns if is already available, but it ended up being quite complicated and lots of extra new code.

Comment (jimmygchen) [reply beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs]: Removed

File: beacon_node/beacon_chain/src/data_availability_checker.rs [hunk 2]
```diff
@@ -346,11 +346,6 @@ impl<T: BeaconChainTypes> DataAvailabilityChecker<T> {
             .put_pending_executed_block(executed_block)
     }
 
-    pub fn remove_pending_components(&self, block_root: Hash256) {
-        self.availability_cache
-            .remove_pending_components(block_root)
-    }
-
```
Comment (jimmygchen) [inline beacon_node/beacon_chain/src/data_availability_checker.rs:353]: This reconstruction error makes the assumption that if the block root doesnt exist, then block is already imported, which is no longer correct. Update error message.

https://github.com/sigp/lighthouse/blob/a134d43446f776fe2a84f420854afbff76ca93d8/beacon_node/beacon_chain/src/data_availability_checker.rs#L590-L595

File: beacon_node/beacon_chain/src/data_availability_checker.rs
Comment (michaelsproul) [inline beacon_node/beacon_chain/src/data_availability_checker.rs:1]: I think we should also update this comment in this file:

```rust
/// Under normal conditions, the cache should only store the current pending block, but could
///  occasionally spike to 2-4 for various reasons e.g. components arriving late, but would very
/// rarely go above this, unless there are many concurrent forks.
```

Now we expect this cache to basically be full all the time

**Review by michaelsproul — APPROVED** [review]
This looks safe to me, and I like the more "idempotent" design style of keeping components rather than removing them.

I still feel like our caches could do with an overhaul and simplification, but that can wait.

File: beacon_node/beacon_chain/src/data_availability_checker.rs
Comment (jimmygchen) [reply beacon_node/beacon_chain/src/data_availability_checker.rs:1]: Updated in https://github.com/sigp/lighthouse/pull/7961/commits/4d8525ac8c05ea91c185e99c95767a898c7169ff, and also reduced the cache size from 64 to 32.

File: beacon_node/beacon_chain/src/data_availability_checker.rs (hunk 2 above)
Comment (jimmygchen) [reply beacon_node/beacon_chain/src/data_availability_checker.rs:353]: Fixed in https://github.com/sigp/lighthouse/pull/7961/commits/4d8525ac8c05ea91c185e99c95767a898c7169ff. Now returns an error as it's an unexpected scenario.

**Review by michaelsproul — APPROVED** [review]
