### PR TITLE
Follow distance fix

### LINKED ISSUE #1074: Eth1 follow distance not respected
@mpetrunic has noted that `ETH1_FOLLOW_DISTANCE` is not being respected during genesis.

His observation seems valid to me, we should look into this and ensure it is respected.

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

- Resolves #1074

## Proposed Changes

- Fixes a bug raised by @mpetrunic where `ETH1_FOLLOW_DISTANCE` was not respected by the beacon node.
- Adds more `info` and `debug` logs for eth1 following actions.
- Converts some single-variant enums into structs (code-quality)

### CODE REVIEW

File: beacon_node/eth1/src/service.rs [hunk 1]
```diff
@@ -613,7 +631,37 @@ impl Service {
                 cache_4.block_cache.read().len() as i64,
             );
 
-            Ok(BlockCacheUpdateOutcome::Success {
+            let block_cache = service_1.inner.block_cache.read();
+            let latest_block_mins = block_cache
+                .earliest_block_timestamp()
```
Comment (michaelsproul) [inline beacon_node/eth1/src/service.rs:636]: Should this be `latest_block_timestamp`?

Comment (paulhauner) [reply beacon_node/eth1/src/service.rs]: Great pickup, thanks!
