### PR TITLE
Remove VC response signing and fix HTTP error handling

### LINKED ISSUE #4597: Fix HTTP error handling in VC API
## Description

The VC API is affected by the same issue as the BN: https://github.com/sigp/lighthouse/issues/3404

For the BN fix see: https://github.com/sigp/lighthouse/pull/4595

We should port similar changes to the VC API.

### LINKED ISSUE #5423: Remove VC response signing
## Description

Currently the validator client[ signs its responses using a secp256k1 key](https://lighthouse-book.sigmaprime.io/api-vc-sig-header.html). Lighthouse is the only client to do this, and there is no cross-client standardisation on signed responses.

The reasons to keep response signing are:

- It prevents a specific man-in-the-middle attack whereby an attacker sits between the VC API client and the VC. The attacker intercepts requests to the VC. They can use the token to make arbitrary (malicious) requests to the VC, but cannot spoof responses to the client because of the signature. 

The reasons to remove response signing are:

- Nobody (?) verifies response signatures, because the described attack is pretty obscure, and unlikely to occur in practice. Further, an attacker in this position (e.g. thanks to a DNS attack) has the power to wreck the VC pretty comprehensively. The signature just means that once they start doing this, the client is likely to detect the attack. A clever attacker could also just honour all of the client's requests, while using the user's token to make extra malicious requests alongside.
- It makes it more difficult for users to provision VC API keys. The API key currently needs to contain a pubkey derived from a private key, and both files need to be set up by the user. Recently there has been discussion of standardising and simplifying key provision across clients, and our unique response signing scheme would be an impediment to this (https://github.com/ethereum/keymanager-APIs/pull/74). In contrast, allowing the API key to be an arbitrary string of bytes is much better for UX.
- Simpler implementation (delete all signing code).
- Less overhead on sending responses (I haven't checked the perf impact of signing)

## Version

Lighthouse v5.1.0

## Steps to resolve

We'll leave this issue open for comments from users & developers. If no compelling argument is made for keeping response signing, then I think it should be removed.

## Additional Info

Related:

- https://github.com/sigp/lighthouse/issues/3446

### PR DESCRIPTION
**Pull request by eserilev**
## Issue Addressed

#4597 and #5423

## Proposed Changes

- Removed VC response signing and related code paths
- prevent warp backtracking issues by changing our usage of `and_then` to `then`

Closes #4597
Closes #5423

### CODE REVIEW

File: common/eth2/src/lighthouse_vc/http_client.rs [hunk 1]
```diff
@@ -78,14 +67,11 @@ pub fn parse_pubkey(secret: &str) -> Result<Option<PublicKey>, Error> {
...
-    /// Create a new client pre-initialised with an API token.
-    pub fn new(server: SensitiveUrl, secret: String) -> Result<Self, Error> {
+    /// Create a new client.
+    pub fn new(server: SensitiveUrl) -> Result<Self, Error> {
         Ok(Self {
             client: reqwest::Client::new(),
             server,
-            server_pubkey: parse_pubkey(&secret)?,
-            secret: Some(secret.into()),
-            authorization_header: AuthorizationHeader::Bearer,
```
Comment (michaelsproul) [inline common/eth2/src/lighthouse_vc/http_client.rs:88]: Ooh, this is deleting a little too much. We need to keep the `Authorization` header on both the client and server side. We just need to change the authentication token to an arbitrary byte string, rather than a token derived from the server's signing key.

File: validator_client/src/http_api/api_secret.rs [hunk 2]
```diff
@@ -1,211 +0,0 @@
...
-
-/// Length of the raw secret key, in bytes.
-pub const SK_LEN: usize = 32;
-
-/// The name of the file which stores the public key.
-///
-/// For users, this public key is a "secret" that can be shared with API consumers to provide them
-/// access to the API. We avoid calling it a "public" key to users, since they should not post this
-/// value in a public forum.
-pub const PK_FILENAME: &str = "api-token.txt";
```
Comment (michaelsproul) [inline validator_client/src/http_api/api_secret.rs:24]: For backwards compatibility, lets keep loading the contents of the `api-token.txt` and using that as the token. We can just ignore the old `.secp-sk` file which contains the secret key.

To generate new tokens we can use a random string of bytes, rather than `api-token-0xpubkey`

**Comment by eserilev** [comment]
I've reverted some of my deletions and refactored a few things

### Removing VC response signing

I've removed VC response signing which makes VC response error handling much simpler. Everything is now wrapped in a `blocking_json_task` which also converts warp errors into `Responses` to prevent weird warp backtrace nonsense

### VC Auth header

I've reverted the changes that removed VC auth header logic. 

> We just need to change the authentication token to an arbitrary byte string, rather than a token derived from the server's signing key.

In `ApiSecret::create_or_open` 

https://github.com/sigp/lighthouse/blob/afccdf84b1b9067ea35acc4f4cededf769574c7f/validator_client/src/http_api/api_secret.rs#L45-L47

This little snippet already randomly generates an auth token. I've removed the following logic

- Generating the server signing key from the api token
- Storing/loading the server signing key on/from disk
- Checking that the server signing key and api token are a valid key pair

I've also ensured that we're still backwards compatible, by loading the api token from disk if it already exists

File: validator_client/src/http_api/api_secret.rs [hunk 3]
```diff
@@ -28,47 +18,34 @@ pub const PK_FILENAME: &str = "api-token.txt";
...
+    /// If the public key file is missing on disk, create a new key and
     /// write it to disk (over-writing any existing files).
     pub fn create_or_open<P: AsRef<Path>>(dir: P) -> Result<Self, String> {
-        let sk_path = dir.as_ref().join(SK_FILENAME);
         let pk_path = dir.as_ref().join(PK_FILENAME);
 
-        if !(sk_path.exists() && pk_path.exists()) {
+        if !pk_path.exists() {
             let sk = SecretKey::random(&mut thread_rng());
             let pk = PublicKey::from_secret_key(&sk);
```
Comment (michaelsproul) [inline validator_client/src/http_api/api_secret.rs]: I think we should go a little further and remove the concept of the token being a public key. We should just generate a random string if the file doesn't exist.

If it does exist, then we shouldn't expect it to start with `PK_PREFIX` (I think we should delete `PK_PREFIX` from the codebase) and we shouldn't try to parse it as hex or using `PublicKey::parse_compressed`.

This will be backwards-compatible because we can support any arbitrary string as the token:

```
# fine
api-token-0xabcdef...ffff
# also fine
hello_world
# also fine
567asd9768sad786sa8d7687as6d
```

It's also more flexible, because people defining their own token don't need to worry about adding the prefix (easy enough), or making the key a valid secp256k1 key (more complicated).

File: common/eth2/src/lighthouse_vc/http_client.rs [hunk 4]
```diff
@@ -263,7 +230,10 @@ impl ValidatorClientHttpClient {
     /// Perform a HTTP GET request, returning `None` on a 404 error.
     async fn get_opt<T: DeserializeOwned, U: IntoUrl>(&self, url: U) -> Result<Option<T>, Error> {
         match self.get_response(url).await {
-            Ok(resp) => self.signed_json(resp).await.map(Option::Some),
+            Ok(resp) => {
+                let body = resp.bytes().await.map_err(Error::from)?;
+                serde_json::from_slice(&body).map_err(Error::InvalidJson)
```
Comment (michaelsproul) [inline common/eth2/src/lighthouse_vc/http_client.rs]: I think you need the `.map(Option::Some)` here, otherwise `serde_json` will try to decode an `Option<T>` rather than a `T`. It's probably fine most of the time, but might be weird if the server sent back `null` which could decode to `None`.

**Review by michaelsproul — CHANGES_REQUESTED** [review]
Looking good! I think we can get this in for v5.2.0 pretty soon

File: validator_client/src/http_api/api_secret.rs (hunk 3 above)
Comment (eserilev) [reply validator_client/src/http_api/api_secret.rs]: I've removed the concept of public tokens, pk prefix, and hex parsing. The api key should be backwards compatible with existing keys, and for new keys it should just be a randomly generated string. There was also some minor refactoring done to remove some redundant fields

changes are in f270e02

File: common/eth2/src/lighthouse_vc/http_client.rs (hunk 4 above)
Comment (eserilev) [reply common/eth2/src/lighthouse_vc/http_client.rs]: fixed in f270e02

File: validator_client/src/http_api/api_secret.rs [hunk 5]
```diff
@@ -1,164 +1,76 @@
...
-pub const SK_FILENAME: &str = ".secp-sk";
-
-/// Length of the raw secret key, in bytes.
-pub const SK_LEN: usize = 32;
-
 /// The name of the file which stores the public key.
 ///
 /// For users, this public key is a "secret" that can be shared with API consumers to provide them
 /// access to the API. We avoid calling it a "public" key to users, since they should not post this
 /// value in a public forum.
```
Comment (michaelsproul) [inline validator_client/src/http_api/api_secret.rs]:
```suggestion
/// The name of the file which stores the API token.
```

**Review by michaelsproul — APPROVED** [review]
Looks great, let's do it!

**Comment by michaelsproul** [comment]
Marking as `backwards-incompat` because removing the `Signature` header is technically a breaking change for the ~0 users who care about this :grin:

Let's merge

**Comment by michaelsproul** [comment]
@mergify queue
