### PR TITLE
Use SignatureBytes and PublicKeyBytes for deposits

### LINKED ISSUE #384: Deposit signatures & pubkeys may not be valid BLS
## Description

The deposit contract does not verify BLS signatures or pubkeys and therefore they may contain arbitrary bytes.

Presently we would fail to parse any `Deposit` with an invalid signature or pubkey, this is a consensus-breaking bug.

## Steps to resolve

My suggestion is to create a `MaybeInvalidSignature` (or more aptly named) wrapper around `Signature` that permits parsing invalid bytes and implement it only for `Deposit`. That way we get to keep our parsing safety for other objects.

EDIT: I updated this issue because it needs to cover `PublicKey` as well as `Signature`.

### PR DESCRIPTION
**Pull request by blacktemplar**
SignatureBytes handles signatures stored in bytes and only parses the bytes when the signature is needed. Therefore SignatureBytes never throws errors except when the signature is parsed (which is then handled directly in verify_deposit.

## Issue Addressed

resolves #384

## Proposed Changes

Adds new struct SignatureBytes. Replaces Signature in Deposit by SignatureBytes.

### CODE REVIEW

File: eth2/utils/bls/src/signature_bytes.rs [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+
+    pub fn new(signature: Signature) -> Self {
+        Self(Self::get_bytes(signature.as_bytes().as_slice()))
+    }
+
+    pub fn as_bytes(&self) -> Vec<u8> {
+        self.0.to_vec()
+    }
+
+    pub fn parse_signature(&self) -> Result<Signature, DecodeError> {
```
Comment (paulhauner) [inline eth2/utils/bls/src/signature_bytes.rs]: I'd be tempted to use a [`TryInto`](https://doc.rust-lang.org/std/convert/trait.TryInto.html) impl instead of this function, primarily because it will allow for easier compatibility with the `fake_crypto` feature.

If we do `TryInto`/`TryFrom` for `Signature` and `FakeSignature` it'll avoid having to create a `parse_signature -> Signature` and `parse_signature -> FakeSignature` (with a `cfg` attribute doing the switch for `fake_crypto`).

Comment (blacktemplar) [reply eth2/utils/bls/src/signature_bytes.rs]: I implemented now TryInto<Signature> for &SignatureBytes and From<Signature> for SignatureBytes. Or do I need to add anything else? I am not very familiar with the fake_crypto concept.

**Comment by blacktemplar** [comment]
Added now also a PublicKeyBytes class.

File: eth2/state_processing/src/per_block_processing/verify_deposit.rs [hunk 2]
```diff
@@ -10,19 +11,22 @@ pub fn verify_deposit_signature<T: EthSpec>(
...
+    match parsed_signature {
+        Err(_) => Err(Error::Invalid(Invalid::BadSignatureBytes)),
+        Ok(signature) => {
+            verify!(
+                signature.verify(&deposit.data.signed_root(), domain, pubkey,),
+                Invalid::BadSignature
+            );
+            Ok(())
+        }
+    }
```
Comment (michaelsproul) [inline eth2/state_processing/src/per_block_processing/verify_deposit.rs]: Just a minor style thing, but this could be written:

```rust
    let signature: Signature = (&deposit.data.signature)
        .try_into()
        .map_err(|_| Error::Invalid(Invalid::BadSignatureBytes))?;

    verify!(
        signature.verify(&deposit.data.signed_root(), domain, pubkey),
        Invalid::BadSignature
    );

    Ok(())
```

Which is a bit clearer IMO.

File: eth2/utils/bls/src/macros.rs [hunk 3]
```diff
@@ -84,3 +84,112 @@ macro_rules! impl_cached_tree_hash {
...
+
+            fn try_into(self) -> Result<$type, Self::Error> {
+                <$type>::from_bytes(&self.0[..])
+            }
+        }
+
+        impl std::convert::From<$type> for $name {
+            fn from(obj: $type) -> Self {
+                // how to avoid this unwrap? We know that obj.as_bytes() always has exactly
+                // $byte_size many bytes.
```
Comment (michaelsproul) [inline eth2/utils/bls/src/macros.rs]: I think an `unwrap` (or an `expect`) is OK here, as we know that the SSZ representation of a pubkey/signature is the right size, but can't encode that in a way the compiler will understand. If you add a test that checks `PublicKeyBytes::from(pubkey)` and `SignatureBytes::from(signature)` then we'll be sure to catch this issue if the SSZ size of these structs ever changes.

Comment (blacktemplar) [reply eth2/utils/bls/src/macros.rs]: I added now tests to check the length of a public key and a signature (but not in the ..Bytes file but directly in Signature and PublicKey). There are already tests for PublicKeyBytes::from and SignatureBytes::from (see PublicKeyBytes::tests::test_valid_public_key and SignatureBytes::tests::test_valid_signature)

**Comment by blacktemplar** [comment]
Added additional length tests and style improvement suggested by @michaelsproul.
