### PR TITLE
Handle unknown head during attestation publishing

### LINKED ISSUE #4699: Handle unknown head block during attestation publishing
## Description

Presently if an attestation is POSTed to the beacon node for a head block that hasn't finished being imported, Lighthouse will log a nasty `ERRO`:

> ERRO Failure verifying attestation for gossip, attestation_slot: XX, committee_index: XX, request_index: X, error: UnknownHeadBlock { beacon_block_root: 0xa98ce8635c5493907d6536905b46eb09db54f8465a82d95aae90650509884f4a }

It will also return a `400 BAD REQUEST` to the VC, which creates a knock-on effect. There's an old issue about this here #1971, which was closed because we started queueing attestations _from gossip_ in #635. We still don't have any queueing for attestations from the HTTP API, which is why this error occurs.

In practice, this will often be encountered by users running Vouch – which broadcasts attestations to all nodes, regardless of whether they already know the head block.

## Version

Lighthouse v4.4.1 and older

## Present Behaviour

- Lighthouse rejects any attestation received on the HTTP API that doesn't immediately pass gossip validation. This includes attestations for blocks that are in the process of being imported.

## Expected Behaviour

- Lighthouse queues attestations received on the HTTP API so that it can:
  - Return a 200 OK to the caller, and
  - Not log an error message

## Steps to resolve

In terms of implementation I think we could use the reprocessing queue. The hard part is blocking the HTTP handler waiting for the attestation to be dequeued and processed. I had a go at implementing something similar for blocks in #4643, which wasn't merged because it ended up being poorly suited to the problem it was trying to solve. We could probably adapt that code, particularly the use of a channel to send back the completion message, and use it for attestations. We could even extend the existing attestation reprocessing logic with an optional channel that gets initialized (and waited on) only for HTTP attestations.

### PR DESCRIPTION
**Pull request by michaelsproul**
## Issue Addressed

Closes #4699

## Proposed Changes

Reprocess attestations received via HTTP which reference unknown blocks. This should reduce false positive logs on BNs used in multi-BN setups, where the VC might send our BN an attestation from another BN before we've finished processing the head block. This applies both to Vouch and the Lighthouse v4.6.0+ VC using `--broadcast attestations`.

In order to avoid blocking a beacon processor thread waiting for the reprocessing to complete, the implementation does the first round of processing in the beacon processor, then uses a `join` to wait for the reprocess futures _from the Tokio executor_. In practice this should be  efficient, as Tokio will park the task until all its reprocess futures are ready, and the beacon processor can continue to churn through work.

### CODE REVIEW

**Comment by dong77** [comment]
Waiting for this to be released as I'm seeing a lot of related errors.

**Comment by michaelsproul** [comment]
@dong77 While this error is annoying, fixing it will only marginally improve performance. If you see this, it means one of your BNs (the one that created the attestation) is ahead of one of your other BNs in terms of blocks imported. If you broadcast the attestation to both of them, then the one that created the attestation (which is "ahead") will process and publish the attestation just fine, while the other one (which is "behind") will log this error. With the change from this PR, both will process and publish and no errors will be logged. So it's just a bit of redundancy during publishing.

File: beacon_node/http_api/src/publish_attestations.rs [hunk 1]
```diff
@@ -0,0 +1,292 @@
...
+        .send(NetworkMessage::Publish {
+            messages: vec![PubsubMessage::Attestation(Box::new((
+                attestation.subnet_id(),
+                attestation.attestation().clone(),
+            )))],
+        })
+        .map_err(|_| Error::Publication)?;
+
+    // Notify the validator monitor.
+    chain
```
Comment (jimmygchen) [inline beacon_node/http_api/src/publish_attestations.rs:96]: Small order change here which seems intentional and reasonable, but thought I'd confirm anyway - we previously notify the monitor first - so it gets tracked regardless of whether publish is successful, was the original behaviour a bug thats fixed here?

Comment (michaelsproul) [reply beacon_node/http_api/src/publish_attestations.rs:96]: Yeah I think this order makes more sense:

- Attestations only get tracked if we published them successfully, and
- We prioritise publishing ASAP.

File: beacon_node/http_api/src/publish_attestations.rs [hunk 2]
```diff
@@ -0,0 +1,292 @@
...
+            }
+        })
+        .unzip();
+    let reprocess_results = futures::future::join_all(reprocess_futures).await;
+
+    // Join everything back together and construct a response.
+    // This part should be quick so we just stay in the Tokio executor's async task.
+    for (i, reprocess_result) in reprocess_indices.into_iter().zip(reprocess_results) {
+        let Some(result_entry) = prelim_results.get_mut(i) else {
+            continue;
```
Comment (jimmygchen) [inline beacon_node/http_api/src/publish_attestations.rs:238]: This would be an unreachable scenario right? Is it worth logging an error here in case if we hit this line?

File: beacon_node/http_api/src/publish_attestations.rs [hunk 3]
```diff
@@ -0,0 +1,292 @@
...
+            &chain.slot_clock,
+        );
+
+    let fc_result = chain.apply_attestation_to_fork_choice(&attestation);
+    let naive_aggregation_result = chain.add_to_naive_aggregation_pool(&attestation);
+
+    if let Err(e) = fc_result {
+        Err(Error::ForkChoice(e))
+    } else if let Err(e) = naive_aggregation_result {
+        Err(Error::AggregationPool(e))
```
Comment (jimmygchen) [inline beacon_node/http_api/src/publish_attestations.rs:126]: We previously capture both errors - is it worth keeping both? i.e. returning a list of errors?

**Review by jimmygchen — COMMENTED** [review]
The changes looks good to me! Just a few minor questions and an annoying `unused` beta compiler error to fix!

File: beacon_node/http_api/src/publish_attestations.rs [hunk 4]
```diff
@@ -0,0 +1,292 @@
...
+                        &attestation,
+                        seen_timestamp,
+                        &network_tx,
+                    ) {
+                        Ok(()) => PublishAttestationResult::Success,
+                        Err(Error::Validation(AttestationError::UnknownHeadBlock {
+                            beacon_block_root,
+                        })) => {
+                            let Some(reprocess_tx) = &reprocess_send else {
+                                return PublishAttestationResult::Failure(Error::ReprocessDisabled);
```
Comment (jimmygchen) [inline beacon_node/http_api/src/publish_attestations.rs:167]: Just a note while reviewing  - was thinking whether we keep the original error, but realise it's probably not worth it
1. beacon processor are enabled by default
2. this is the only usage of `ReprocessDisabled`, if we get this we know we've got an `UnknownHeadBlock` - if we do re-procssing in more scenarios in the future it might be worth keeping the original error.

File: beacon_node/http_api/src/publish_attestations.rs (hunk 3 above)
Comment (michaelsproul) [reply beacon_node/http_api/src/publish_attestations.rs:126]: I'll add some logs. I don't think the errors are particularly useful to send in the response, as the caller can't parse them and probably can't do anything. An error here means the attestation is really poor quality, or there is some serious bug.

**Comment by michaelsproul** [comment]
I did some benchmarking with `--subscribe-all-subnets` and attestation packing was taking 100-250ms regularly. I think we need the thread pool. I will add a non-Rayon threadpool when I have some time. Until then I'll bump this from the v5.0.0 release, which needs to happen next week.

**Comment by michaelsproul** [comment]
Ignore previous comment (now deleted). I commented on the wrong issue.

File: beacon_node/http_api/src/publish_attestations.rs (hunk 2 above)
Comment (michaelsproul) [reply beacon_node/http_api/src/publish_attestations.rs:238]: Logging added in 6043b0cca1674ee3b78099d3c82c863d76944a10

File: beacon_node/http_api/src/publish_attestations.rs (hunk 3 above)
Comment (michaelsproul) [reply beacon_node/http_api/src/publish_attestations.rs:126]: Logging added in 6043b0cca1674ee3b78099d3c82c863d76944a10

**Comment by dong77** [comment]
> @dong77 While this error is annoying, fixing it will only marginally improve performance. If you see this, it means one of your BNs (the one that created the attestation) is ahead of one of your other BNs in terms of blocks imported. If you broadcast the attestation to both of them, then the one that created the attestation (which is "ahead") will process and publish the attestation just fine, while the other one (which is "behind") will log this error. With the change from this PR, both will process and publish and no errors will be logged. So it's just a bit of redundancy during publishing.

Is there a way to disable/hide this error?

**Comment by michaelsproul** [comment]
> Is there a way to disable/hide this error?

No

**Review by jimmygchen — APPROVED** [review]
LGTM!

**Comment by jimmygchen** [comment]
@mergify queue

**Comment by jimmygchen** [comment]
@mergify unqueue

**Comment by jimmygchen** [comment]
@michaelsproul did you want to include this in the next release? just saw your comment in the description regarding needing further testing, so I've unqueued this for now

**Comment by michaelsproul** [comment]
@jimmygchen I'd like to include it. I think the current test demonstrates that it's working, and we'll get a few days to observe on testnets once we've merged

**Comment by michaelsproul** [comment]
@mergifyio requeue
